version: '3.4'
name: vuejs3_net8
services:
  #vuejs3_net8_sqlserver:
  #  image: vuejs3_net8_sqlserver
  #  container_name: vuejs3_net8_sqlserver
  #  build: 
  #    context: ./var/database/sql_server
  #    dockerfile: ./Dockerfile
  #  volumes:
  #    - vuejs3_net8_sqlserver_data:/var/opt/mssql
  #  ports:
  #    - 1433:1433
  vuejs3_net8_sqlserver:
    image: vuejs3_net8_sqlserver
    container_name: vuejs3_net8_sqlserver
    build: 
      context: ./var/database/sql_server_no_scripts
      dockerfile: ./Dockerfile
    volumes:
      - vuejs3_net8_sqlserver_data:/var/opt/mssql
    ports:
      - 1433:1433

  vuejs3_net8_be:
    image: vuejs3_net8_be
    container_name: vuejs3_net8_be
    build:
      context: ./be
      dockerfile: ./Dockerfile
    ports:
      - 5179:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=File
      - Serilog__WriteTo__1__Args__path=Logs\\Logs.txt
      - Serilog__WriteTo__1__Args__outputTemplate={Timestamp} {Message}{NewLine:1}{Exception:1}
      - Serilog__WriteTo__1__Args__rollingInterval=Day
      - Serilog__WriteTo__2__Name=MSSqlServer
      - Serilog__WriteTo__2__Args__connectionString=Server=vuejs3_net8_sqlserver;Database=AuthDB;User id=sa;Password=Password01!;TrustServerCertificate=True
      - Serilog__WriteTo__2__Args__tableName=Logs
      - Serilog__WriteTo__2__Args__AutoCreateSqlTable=True     
      - ConnectionStrings__AuthDB_SQLServer=Server=vuejs3_net8_sqlserver;Database=AuthDB;User id=sa;Password=Password01!;TrustServerCertificate=True;
    links:
      - vuejs3_net8_sqlserver

  vuejs3_net8_fe:
    image: vuejs3_net8_fe
    container_name: vuejs3_net8_fe
    build:
      context: ./fe
      dockerfile: ./Dockerfile
    ports: 
      - 5173:80
    links:
      - vuejs3_net8_be

  vuejs3_net8_prometheus:
    image: prom/prometheus:v2.48.0
    container_name: vuejs3_net8_prometheus
    #ports:
    #  - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./var/monitoring/prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
      - vuejs3_net8_prometheus_data:/prometheus
    #restart: unless-stopped

  #questo è per le risorse dei containers in linux
  vuejs3_net8_cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0     
    container_name: vuejs3_net8_cadvisor
    #ports:
    #  - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    #restart: unless-stopped

  #questo è per le risorse di sistema in linux
  vuejs3_net8_node_exporter:
   image: quay.io/prometheus/node-exporter:v1.5.0
   container_name: vuejs3_net8_node_exporter
   command: "--path.rootfs=/host"
   pid: host
   #restart: unless-stopped
   volumes:
     - /:/host:ro,rslave

  vuejs3_net8_grafana:
    image: grafana/grafana-oss:10.2.2
    container_name: vuejs3_net8_grafana
    ports:
      - "3000:3000"
    volumes:
      - vuejs3_net8_grafana_data:/var/lib/grafana
    #restart: unless-stopped

volumes:
  vuejs3_net8_sqlserver_data:
    name: vuejs3_net8_sqlserver_data
    driver: local
  vuejs3_net8_prometheus_data:
    name: vuejs3_net8_prometheus_data
    driver: local
  vuejs3_net8_grafana_data:
    name: vuejs3_net8_grafana_data
    driver: local